### ISSUE TITLE
Cannot call `.save()` multiple times

### ISSUE THREAD

**Issue by jacobq** [pouchdb-community/ember-pouch#239]
It seems that calling `.save()` on a record multiple times without waiting for the previous promise(s) to resolve leads to an error being thrown. AFAIK, there is nothing [in the ember-data contract](https://www.emberjs.com/api/ember-data/3.5/classes/DS.Model/methods/save?anchor=save) that prohibits this (though it seems rather pointless in this example).

Reproduction repo here: [jacobq/ember-pouch-back-to-back-save](https://github.com/jacobq/ember-pouch-back-to-back-save)

Perhaps this is another manifestation of whatever is causing #237

**Comment by jacobq** [comment]
Looking a little deeper into this, it seems to be because calling `save` results in a Pouch/Couch update regardless of whether or not data has actually changed. In other words, doing `await record.save()` 10 times will make 10 revisions even though the actual data hasn't changed. At least, that's what I'm surmising based on the error message I saw when running this on ember 2.x:
```
Error: Assertion Failed: 'item:A44E0283-8F82-3F6A-9234-BFF0BC19D788' was saved to the server, but the response returned the new id '223A8B1B-3581-4EB2-829B-D6610FE97C0F'. The store cannot assign a new id to a record that already has an id.
    at new EmberError (http://localhost:7357/assets/vendor.js:24386:25)
    at Object.assert (http://localhost:7357/assets/vendor.js:24629:15)
    at Class.updateId (http://localhost:7357/assets/vendor.js:101057:60)
    at Class.didSaveRecord (http://localhost:7357/assets/vendor.js:100998:12)
...
```

Without much knowledge of PouchDB/CouchDB, it seems to me that there is some kind of coupling between revisions or IDs in PouchDB/CouchDB and those in ember-data. If that is the case, isn't that bad? For one, it means that doing this will be problematic:

```js
const createSpecialPersonRecord = () => store.createRecord('person', { id: 'special_id' });
let record = createSpecialPersonRecord();
await record.save();
await record.destroyRecord();
// ...
record = createSpecialPersonRecord(); // will throw error about ID already having been used
// ...
```

See also https://github.com/jacobq/ember-pouch-back-to-back-save-2x

**Comment by jacobq** [comment]
One way to work around this "back-to-back" problem is to modify our implementation of [`Adapter.createRecord`](https://github.com/pouchdb-community/ember-pouch/blob/master/addon/adapters/pouch.js#L468) so that it detects this case, e.g.:

```js
createRecord: function(store, type, snapshot) {
  const record = snapshot.record;
  if (record._emberPouchSavePromise) {
    // `createRecord` has been called with this record before, 
    // so we don't want to actually create another entry in the DB this time
    return record._emberPouchSavePromise;
  }

  this._init(store, type);
  var data = this._recordToData(store, type, snapshot);
  let rel = this.get('db').rel;

  let id = data.id;
  if (!id) {
    id = data.id = rel.uuid();
  }
  this.createdRecords[id] = true;
  // Save a reference to this promise in case duplicate calls are made on this record
  record._emberPouchSavePromise = rel.save(this.getRecordTypeName(type), data).catch((e) => {
    delete this.createdRecords[id];
    throw e;
  });
  return record._emberPouchSavePromise;
},
```

**Comment by jlami** [comment]
I'm not sure if just dropping the second save would work. Because the record could have changed between the two calls, so we still should persist any changes.

I'm not really sure but I think this should be fixed in ember-data itself. That layer is responsible for all the state tracking and should know whether `save` is actually a correct action at that moment. The second call should then chain onto the first promise so it can see what the response was. And it should call `adapter.updateRecord` instead of `createRecord` if it succeeded, or start another `createRecord` if it failed. Fixing this in ember-pouch feels like the wrong place.

**Comment by jacobq** [comment]
> ...the record could have changed between the two calls, so we still should persist any changes.

I think you're right, but we need to make sure that they get persisted to the correct (same) record (rather than a copy).

> I'm not really sure but I think this should be fixed in ember-data itself. That layer is responsible for all the state tracking and should know whether `save` is actually a correct action at that moment.

I was asking about this in the ember-data Discord channel and got this answer:
"*basically, the adapter needs to decide whether to send a new request if you call save more than once and the previous requests haven't finished*"

**Comment by jlami** [comment]
Wow, I'm not really sure how I feel about that. But if that is really their final answer we indeed have to do something ourselves.

**Comment by runspired** [comment]
> I'm not sure if just dropping the second save would work. Because the record could have changed between the two calls, so we still should persist any changes.

You could always choose to queue and chain saves, or discard the save if it contained the same data as an already pending save request.

> That layer is responsible for all the state tracking

I don't recommend our state tracking, the proliferation of addons for additional state tracking makes it fairly clear that EmberData's is not good enough. It'll get better with time, we have some solid plans for it, but it's kinda far down the roadmap.

> and should know whether save is actually a correct action at that moment.

This is unknowable, and as such will always be an app code decision. Only the developer knows their API contract and the adapter is where the developer aligns the API contract with the requests EmberData is issuing.

That said there are two potential solutions that allow you to continue issuing as many requests as you like.

1) Use `lid` in versions containing the IDENTIFIERS feature flag and have pouch make use of it for either the ID or to ensure that all saves save to a consistent ID.
2) Use `adapter.generateIdForRecord` to assign the ID on the client during creation.

**Comment by runspired** [comment]
P.S. once you have resolved this if you'd like to PR ember-pouch as an external-partner test to EmberData we're always happy to have more test coverage, especially around ensuring common patterns for extending the library continue to work as expected :)
